require 'virtus'
require 'active_support/notifications'
require 'string'
require 'ordoro/version'
require "httparty"

require 'ordoro/client'

require 'ordoro/record/base'
require 'ordoro/record/base_adapter'
require 'ordoro/record/exceptions'
require 'ordoro/record/address'
require 'ordoro/record/comment'
require 'ordoro/record/product'
require 'ordoro/record/tax_line_item'
require 'ordoro/record/order_line_item'
require 'ordoro/record/shipment'
require 'ordoro/record/order'
require 'ordoro/record/order_adapter'
require 'ordoro/record/product_adapter'
